sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/scripts koalaman/shellcheck /OSX-RAMDisk/Contents/MacOS/startupRAMDiskandCacheMover.sh

matrix:
  fast_finish: true
